/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsTeamRouteImport } from './routes/solutions.team'
import { Route as SolutionsTalentRouteImport } from './routes/solutions.talent'
import { Route as SolutionsProjectRouteImport } from './routes/solutions.project'
import { Route as CareersIdRouteImport } from './routes/careers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTeamRoute = SolutionsTeamRouteImport.update({
  id: '/solutions/team',
  path: '/solutions/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTalentRoute = SolutionsTalentRouteImport.update({
  id: '/solutions/talent',
  path: '/solutions/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsProjectRoute = SolutionsProjectRouteImport.update({
  id: '/solutions/project',
  path: '/solutions/project',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIdRoute = CareersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/careers/$id': typeof CareersIdRoute
  '/solutions/project': typeof SolutionsProjectRoute
  '/solutions/talent': typeof SolutionsTalentRoute
  '/solutions/team': typeof SolutionsTeamRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/careers/$id': typeof CareersIdRoute
  '/solutions/project': typeof SolutionsProjectRoute
  '/solutions/talent': typeof SolutionsTalentRoute
  '/solutions/team': typeof SolutionsTeamRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/careers/$id': typeof CareersIdRoute
  '/solutions/project': typeof SolutionsProjectRoute
  '/solutions/talent': typeof SolutionsTalentRoute
  '/solutions/team': typeof SolutionsTeamRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/industries'
    | '/locations'
    | '/privacy'
    | '/sitemap.xml'
    | '/careers/$id'
    | '/solutions/project'
    | '/solutions/talent'
    | '/solutions/team'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/industries'
    | '/locations'
    | '/privacy'
    | '/sitemap.xml'
    | '/careers/$id'
    | '/solutions/project'
    | '/solutions/talent'
    | '/solutions/team'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/industries'
    | '/locations'
    | '/privacy'
    | '/sitemap.xml'
    | '/careers/$id'
    | '/solutions/project'
    | '/solutions/talent'
    | '/solutions/team'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CareersRoute: typeof CareersRouteWithChildren
  IndustriesRoute: typeof IndustriesRoute
  LocationsRoute: typeof LocationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsProjectRoute: typeof SolutionsProjectRoute
  SolutionsTalentRoute: typeof SolutionsTalentRoute
  SolutionsTeamRoute: typeof SolutionsTeamRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/team': {
      id: '/solutions/team'
      path: '/solutions/team'
      fullPath: '/solutions/team'
      preLoaderRoute: typeof SolutionsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/talent': {
      id: '/solutions/talent'
      path: '/solutions/talent'
      fullPath: '/solutions/talent'
      preLoaderRoute: typeof SolutionsTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/project': {
      id: '/solutions/project'
      path: '/solutions/project'
      fullPath: '/solutions/project'
      preLoaderRoute: typeof SolutionsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$id': {
      id: '/careers/$id'
      path: '/$id'
      fullPath: '/careers/$id'
      preLoaderRoute: typeof CareersIdRouteImport
      parentRoute: typeof CareersRoute
    }
  }
}

interface CareersRouteChildren {
  CareersIdRoute: typeof CareersIdRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersIdRoute: CareersIdRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CareersRoute: CareersRouteWithChildren,
  IndustriesRoute: IndustriesRoute,
  LocationsRoute: LocationsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsProjectRoute: SolutionsProjectRoute,
  SolutionsTalentRoute: SolutionsTalentRoute,
  SolutionsTeamRoute: SolutionsTeamRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
